import ogImg from "@/assets/others/OG.png";
import type { Metadata } from "next";

export const RootMetadata: Metadata = {
  title: "Md Kawsar Islam Yeasin",
  description:
    " I am yeasin form Dhaka and I am 21 year old. I'm a self-taught front-end focused Full Stack Web Developer. TypeScript and Nextjs enthusiast. I have been doing freelance project from last 1 year and working with teams to make good projects..",
  authors: [{ name: "Md Kawsar Islam Yeasin" }],
  category: "Software Development",
  keywords: [
    "Md Kawsar Islam Yeasin",
    "Software Developer",
    "Web Developer",
    "yeasin",
    "yeasin2002",
    "Md Kawsar Islam Yeasin",
    "kawsar",
    "Md kawsar",
    "dev yeasin",

    // Extra 😹
    "Software Developer",
    "Web Developer",
    "Full Stack Developer",
    "Frontend Developer",
    "Backend Developer",
    "JavaScript Developer",
    "Python Developer",
    "Java Developer",
    "Next.js Developer",
    "Supabase Developer",
    "React Developer",
    "Node.js Developer",
    "Express.js Developer",
    "Vue.js Developer",
    "Angular Developer",
    "HTML",
    "CSS",
    "Sass",
    "Less",
    "Tailwind CSS",
    "Bootstrap",
    "SQL",
    "NoSQL",
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "Firebase",
    "AWS",
    "Azure",
    "Google Cloud",
    "Docker",
    "Kubernetes",
    "CI/CD",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "RESTful API",
    "GraphQL",
    "Microservices",
    "Agile Development",
    "Scrum",
    "JIRA",
    "Trello",
    "Confluence",
    "Jenkins",
    "Travis CI",
    "CircleCI",
    "Web Development",
    "Software Engineering",
    "Responsive Design",
    "Cross-browser Compatibility",
    "Performance Optimization",
    "Unit Testing",
    "Integration Testing",
    "End-to-End Testing",
    "Test-Driven Development",
    "Behavior-Driven Development",
    "Code Review",
    "Pair Programming",
    "Version Control",
    "Technical Documentation",
    "Project Management",
    "Software Architecture",
    "DevOps",
    "API Integration",
    "Cloud Computing",
    "Data Structures",
    "Algorithms",
    "Cybersecurity",
    "Debugging",
    "Problem Solving",
    "Team Collaboration",
    "Communication Skills",
    "Leadership Skills",
    "Dhaka Developer",
    "Chittagong Developer",
    "Bangladesh Developer",
    "Bangladeshi Programmer",
    "Bangladesh Tech",
    "Bangladesh IT",
    "Bangladesh Software Engineer",
    "Bangladesh Web Engineer",
    "Bangladesh Tech Community",
    "Dhaka Tech",
    "Chittagong Tech",
    "Bangladesh Web Projects",
    "Bangladesh Tech Talent",
    "Bangladesh Innovation",
    "Bangladesh App Developer",
    "Bangladesh Digital Solutions",
    "Bangladesh Software Solutions",
    "Bangladesh Web Development",
    "Bangladesh IT Services",
    "Bangladesh Developer Community",
  ],

  openGraph: {
    title: "Md Kawsar Islam Yeasin",
    description:
      "Portfolio of  Md Kawsar Islam Yeasin , a software Developer,Front end web developer, web developer and web designer,programmer,  from Bangladesh.",
    type: "website",
    locale: "en_IE",
    url: "https://yeasin2002.vercel.app/",
    siteName: "Md Kawsar Islam Yeasin",
    emails: "mdkawsarislam2002@gmail.com",
    countryName: "Bangladesh",
    images: [
      {
        url: ogImg.src,
        width: 1200,
        height: 630,
        alt: "Md Kawsar Islam Yeasin",
      },
    ],
  },
  metadataBase: new URL("https://yeasin2002.vercel.app"),
};
